config/routes.rb
Rails.application.routes.draw do
  get 'moderator/load_term_data_from_json', as: :term_data

  post 'moderator/load_term_data_from_json_commit', as: :term_data_commit

  devise_for :admins
  resources :permition_roles
  resources :right_group_permitions
  resources :role_group_rights
  resources :permitions
  resources :group_rights
  resources :role_users
  resources :dictionary_accesses do
    collection do
      get :get_table
    end
  end
  resources :information_systems
  resources :roles
  resources :users
  resources :branch_trees
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dictionary_accesses_controller.rb
class DictionaryAccessesController < ApplicationController
  before_action :set_dictionary_access, only: [:show, :edit, :update, :destroy]

  # GET /dictionary_accesses
  # GET /dictionary_accesses.json
  def index
    @dictionary_accesses = DictionaryAccess.all.page(params[:page]).per(10)
    @page = params[:page]
    @page = 1 if @page.blank?
  end

  # GET /dictionary_accesses/1
  # GET /dictionary_accesses/1.json
  def show

  end

  # GET /dictionary_accesses/new
  def new
    @dictionary_access = DictionaryAccess.new
  end

  # GET /dictionary_accesses/1/edit
  def edit
  end

  # POST /dictionary_accesses
  # POST /dictionary_accesses.json
  def create
    @dictionary_access = DictionaryAccess.new(dictionary_access_params)

    respond_to do |format|
      if @dictionary_access.save
        format.html { redirect_to @dictionary_access, notice: 'Dictionary access was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary_access }
      else
        format.html { render :new }
        format.json { render json: @dictionary_access.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionary_accesses/1
  # PATCH/PUT /dictionary_accesses/1.json
  def update
    respond_to do |format|
      if @dictionary_access.update(dictionary_access_params)
        format.html { redirect_to @dictionary_access, notice: 'Dictionary access was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary_access }
      else
        format.html { render :edit }
        format.json { render json: @dictionary_access.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def get_table
    dictionary = DictionaryAccess.where(access_key: params['ak1']).first
    @result = ""
    if dictionary
      if dictionary.information_system.access_key == params['ak2']
        begin
          @result = instance_eval("#{dictionary.name}.all")
        rescue
          @result = "Ошибка при составлении JSON"
        end
      else
        @result = "Не найдена информационная система с таким словарем (#{params["ak2"]})"
      end
    else
      @result = "Не найден словарь (#{params["ak1"]})"
    end
    respond_to do |format|
      format.json {render json: @result}
    end
  end
  
  
  # DELETE /dictionary_accesses/1
  # DELETE /dictionary_accesses/1.json
  def destroy
    @dictionary_access.destroy
    respond_to do |format|
      format.html { redirect_to dictionary_accesses_url, notice: 'Dictionary access was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary_access
      @dictionary_access = DictionaryAccess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_access_params
      params.require(:dictionary_access).permit(:information_system_id, :name, :access_key)
    end
end

app/helpers/dictionary_accesses_helper.rb
module DictionaryAccessesHelper
  def link_to_add_dictionary_access(form, person)
    new_object = DictionaryAccess.new()
    fields = form.fields_for(:dictionary_accesses, new_object, 
      :child_index => 'new_dictionary_access') do |builder|
      render('information_systems/add_dictionary_access', fn: builder)
    end
    link_to(?#, class: 'btn btn-outline-primary', 
        id: 'add_dictionary_access_link', data: {content: "#{fields}"}) do 
      " Добавить доступ к словарю" 
    end
  end
  
  def link_to_remove_dictionary_access(form)  
    form.hidden_field(:_destroy, class: 'remove_fields') + 
        link_to(?#, class: 'remove_fields remove_dictionary_access btn btn-danger') do 
          icon('fas', 'times')     
    end
  end
end

app/views/dictionary_accesses/_form.html.haml
= form_for @dictionary_access do |f|
  - if @dictionary_access.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dictionary_access.errors.count, "error")} prohibited this dictionary_access from being saved:"
      %ul
        - @dictionary_access.errors.full_messages.each do |message|
          %li= message

  .lin_gor
  %p
    .row
      .col-md-2
      .lin_ver
      .col-md-6  
        = f.label :information_system
        = f.select :information_system_id, options_for_select(InformationSystem.all.map{|t| ["#{t.name} " , t.id]}, f.object.information_system_id),{include_blank: true},{class:"form-control selectpicker", data: {value: f.object.information_system_id}}
        = f.label :name
        = f.text_field :name, class:"form-control "
        = f.label :access_key
        = f.text_field :access_key, class:"form-control "
    %br
      .row
        .col-md-12
          .col-md-2.col-md-offset-2
            = link_to t('button.back'), dictionary_accesses_path, class: "btn btn-danger"
          .col-md-2
            = f.submit t('button.save'), class: "btn btn-primary"

app/views/dictionary_accesses/edit.html.haml
%h1 Editing dictionary_access

= render 'form'

= link_to 'Show', @dictionary_access
\|
= link_to 'Back', dictionary_accesses_path

app/views/dictionary_accesses/get_table.html.erb
<%= @result%>

app/views/dictionary_accesses/index.html.haml
%h1= t("headers.#{params['controller']}.#{params['action']}")
.card.border-light.mb-3
  .card-header
    = link_to t('button.new.dictionary_access'), new_dictionary_access_path, class:"btn btn-success"
%p.bottom_20
.row
.card.border-light.mb-3
  .card-header
    .col-md-5
      %input{type: "text", id: "input1", class: "form-control", placeholder: "Ключ доступа для словаря"}
    .col-md-5
      %input{type: "text", id: "input2", class: "form-control", placeholder: "Ключ доступа для информационной системы"}
    .col-md-2
      %button#test.btn.btn-success
        Проверка
%p.bottom_20
.table-responsive
  %table.table.table-hover.table-striped.my_table{style: "width:100%;"}
    %thead.thead-dark
      %tr
        %th №
        %th= t('activerecord.attributes.dictionary_access.information_system')
        %th= t('activerecord.attributes.dictionary_access.name')
        %th= t('activerecord.attributes.dictionary_access.access_key')
        %th
    %tbody
      - @dictionary_accesses.each_with_index do |dictionary_access, i|
        %tr
          %td
            =succeed '.' do
              =i + 1 + 10 * (@page.to_i - 1)
          %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{dictionary_access.id}"]}}= dictionary_access.information_system.name
          %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{dictionary_access.id}"]}}= dictionary_access.name
          %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{dictionary_access.id}"]}}= dictionary_access.access_key
          %td= link_to t('button.destroy'), dictionary_access, method: :delete, data: { confirm: t('helpers.sure') }, class:"btn btn-danger"
= paginate @dictionary_accesses, id: "paginate"

app/views/dictionary_accesses/new.html.haml
%h1= t("headers.#{params['controller']}.#{params['action']}")

= render 'form'

app/views/dictionary_accesses/show.html.haml
.card.border-dark.mb-3{:style => "max-width: 60rem;"}
  .card-body
    %table.table_index_base
      %tr
        %th= t('activerecord.attributes.dictionary_access.information_system')
        %td= @dictionary_access.information_system.name 
      %tr
        %th= t('activerecord.attributes.dictionary_access.name')
        %td= @dictionary_access.name
      %tr
        %th= t('activerecord.attributes.dictionary_access.access_key')
        %td= @dictionary_access.access_key
.row
  .col-md-6.col-md-offset-2
    = link_to t('button.edit'), edit_dictionary_access_path(@dictionary_access), class: "btn btn-primary"
    = link_to t('button.back'), dictionary_accesses_path, class: "btn btn-danger"