config/routes.rb
Rails.application.routes.draw do
  get 'moderator/load_term_data_from_json', as: :term_data

  post 'moderator/load_term_data_from_json_commit', as: :term_data_commit

  devise_for :admins
  resources :permition_roles
  resources :right_group_permitions
  resources :role_group_rights
  resources :permitions
  resources :group_rights
  resources :role_users
  resources :dictionary_accesses do
    collection do
      get :get_table
    end
  end
  resources :information_systems
  resources :roles
  resources :users
  resources :branch_trees
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/permition.rb
class Permition < ApplicationRecord
  belongs_to :information_system, inverse_of: :permitions
  has_many :right_group_permitions
  has_many :permition_roles

  
  validates :act, presence: true
  validates :parameter, presence: true
end

app/controllers/permitions_controller.rb
class PermitionsController < ApplicationController
  before_action :set_permition, only: [:show, :edit, :update, :destroy]

  # GET /permitions
  # GET /permitions.json
  def index
    @permitions = Permition.all.page(params[:page]).per(10)
    @page = params[:page]
    @page = 1 if @page.blank?
  end

  # GET /permitions/1
  # GET /permitions/1.json
  def show
  end

  # GET /permitions/new
  def new
    @permition = Permition.new
  end

  # GET /permitions/1/edit
  def edit
  end

  # POST /permitions
  # POST /permitions.json
  def create
    @permition = Permition.new(permition_params)

    respond_to do |format|
      if @permition.save
        format.html { redirect_to @permition, notice: 'Permition was successfully created.' }
        format.json { render :show, status: :created, location: @permition }
      else
        format.html { render :new }
        format.json { render json: @permition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permitions/1
  # PATCH/PUT /permitions/1.json
  def update
    respond_to do |format|
      if @permition.update(permition_params)
        format.html { redirect_to @permition, notice: 'Permition was successfully updated.' }
        format.json { render :show, status: :ok, location: @permition }
      else
        format.html { render :edit }
        format.json { render json: @permition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permitions/1
  # DELETE /permitions/1.json
  def destroy
    @permition.destroy
    respond_to do |format|
      format.html { redirect_to permitions_url, notice: 'Permition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permition
      @permition = Permition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permition_params
      params.require(:permition).permit(:act, :information_system_id, :parameter)
    end
end

app/helpers/permitions_helper.rb
module PermitionsHelper
  def link_to_add_permition(form, person)
    new_object = Permition.new()
    fields = form.fields_for(:permitions, new_object, 
      :child_index => 'new_permition') do |builder|
      render('information_systems/add_permition', fn: builder)
    end
    link_to(?#, class: 'btn btn-outline-success', 
        id: 'add_permition_link', data: {content: "#{fields}"}) do 
      " Новые права на конкретные действия" 
    end
  end
  
  def link_to_remove_permition(form)  
    form.hidden_field(:_destroy, class: 'remove_fields') + 
        link_to(?#, class: 'remove_fields remove_permition btn btn-danger') do 
          icon('fas', 'times')     
    end
  end
end

app/views/permitions/_form.html.haml
= form_for @permition do |f|
  - if @permition.errors.any?
    #error_explanation
      %h2= "#{pluralize(@permition.errors.count, "error")} prohibited this permition from being saved:"
      %ul
        - @permition.errors.full_messages.each do |message|
          %li= message


  %p
  .lin_gor
  %p.bottom_20
    .row
      .col-md-2
      .lin_ver
      .col-md-6
        = f.label :act
        = f.text_field :act, class:"form-control"
        = f.label :information_system
        = f.select :information_system_id, options_for_select(InformationSystem.all.map{|t| ["#{t.name} " , t.id]}, f.object.information_system_id),{include_blank: true},{class:"form-control selectpicker", data: {value: f.object.information_system_id}}
        = f.label :parameter
        = f.text_field :parameter, class:"form-control "
    %br
      .row
        .col-md-12
          .col-md-2.col-md-offset-2
            = link_to t('button.back'), permitions_path, class: "btn btn-danger"
          .col-md-2
            = f.submit t('button.save'), class: "btn btn-primary"

app/views/permitions/edit.html.haml
%h1 Editing permition

= render 'form'

= link_to 'Show', @permition
\|
= link_to 'Back', permitions_path

app/views/permitions/index.html.haml
%h1= t("headers.#{params['controller']}.#{params['action']}")
.card.border-light.mb-3
  .card-header
    = link_to t('button.new.permition'), new_permition_path, class:"btn btn-success"
.table-responsive
  %table.table.table-hover.table-striped.my_table{style: "width:100%;"}
    %thead.thead-dark
      %tr
        %th №
        %th= t('activerecord.attributes.permition.act')
        %th= t('activerecord.attributes.permition.information_system')
        %th= t('activerecord.attributes.permition.parameter')
        %th
    %tbody
      - @permitions.each_with_index do |permition, i|
        %tr
          %td
            =succeed '.' do
              =i + 1 + 10 * (@page.to_i - 1)
          %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{permition.id}"]}}= permition.act
          %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{permition.id}"]}}= permition.information_system.name
          %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{permition.id}"]}}= permition.parameter
          %td= link_to t('button.destroy'), permition, method: :delete, data: { confirm: t('helpers.sure') }, class:"btn btn-danger"
= paginate @permitions, id: "paginate"

app/views/permitions/new.html.haml
%h1= t("headers.#{params['controller']}.#{params['action']}")

= render 'form'

app/views/permitions/show.html.haml
%p#notice= notice

%p
  %b Act:
  = @permition.act
%p
  %b Information system:
  = @permition.information_system
%p
  %b Parameter:
  = @permition.parameter

= link_to 'Edit', edit_permition_path(@permition)
\|
= link_to 'Back', permitions_path