config/routes.rb
Rails.application.routes.draw do
  get 'moderator/load_term_data_from_json', as: :term_data

  post 'moderator/load_term_data_from_json_commit', as: :term_data_commit

  devise_for :admins
  resources :permition_roles
  resources :right_group_permitions
  resources :role_group_rights
  resources :permitions
  resources :group_rights
  resources :role_users
  resources :dictionary_accesses do
    collection do
      get :get_table
    end
  end
  resources :information_systems
  resources :roles
  resources :users
  resources :branch_trees
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group_right.rb
class GroupRight < ApplicationRecord
  belongs_to :information_system
  has_many :role_group_rights
  has_many :right_group_permitions, inverse_of: :group_right
  accepts_nested_attributes_for :right_group_permitions, allow_destroy: true


 
  validates :group_name, presence: true, uniqueness: true
  validates :parameter, presence: true
end

app/controllers/group_rights_controller.rb
class GroupRightsController < ApplicationController
  before_action :set_group_right, only: [:show, :edit, :update, :destroy]

  # GET /group_rights
  # GET /group_rights.json
  def index
    #@group_rights = GroupRight.all
    unless params[:id].nil?
      @group_rights = GroupRight.where(information_system_id: params[:id])
    else
      @group_rights = GroupRight.all
    end
    @group_rights = GroupRight.all.page(params[:page]).per(10)
    @page = params[:page]
    @page = 1 if @page.blank?
  end

  # GET /group_rights/1
  # GET /group_rights/1.json
  def show
  end

  # GET /group_rights/new
  def new
    @group_right = GroupRight.new
  end

  # GET /group_rights/1/edit
  def edit
  end

  # POST /group_rights
  # POST /group_rights.json
  def create
    @group_right = GroupRight.new(group_right_params)

    respond_to do |format|
      if @group_right.save
        format.html { redirect_to @group_right, notice: 'Group right was successfully created.' }
        format.json { render :show, status: :created, location: @group_right }
      else
        format.html { render :new }
        format.json { render json: @group_right.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_rights/1
  # PATCH/PUT /group_rights/1.json
  def update
    respond_to do |format|
      if @group_right.update(group_right_params)
        format.html { redirect_to @group_right, notice: 'Group right was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_right }
      else
        format.html { render :edit }
        format.json { render json: @group_right.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_rights/1
  # DELETE /group_rights/1.json
  def destroy
    @group_right.destroy
    respond_to do |format|
      format.html { redirect_to group_rights_url, notice: 'Group right was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_right
      @group_right = GroupRight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_right_params
      params.require(:group_right).permit(:information_system_id, :group_name, :parameter,
                                  right_group_permitions_attributes: [:id, :_destroy, :permition_id, :parameter])     
    end
end

app/helpers/group_rights_helper.rb
module GroupRightsHelper
end

app/views/group_rights/_add_right_group_permition.haml
.col-md-6
  .panel.panel-info
    .panel-heading
      Новый комментарий
      %span.toright
        = link_to_remove_right_group_permition(fn)
      .clearfix
    .panel-body
      .field
        = fn.label :permition
        = fn.select :permition_id,
        options_for_select(Permition.all.map{|t| ["#{t.act} ", t.id]}, fn.object.permition_id),
        {include_blank: true}
      .field
        = fn.label :parameter
        = fn.text_field :parameter

app/views/group_rights/_form.html.haml
= form_for @group_right do |f|
  - if @group_right.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group_right.errors.count, "error")} prohibited this group_right from being saved:"
      %ul
        - @group_right.errors.full_messages.each do |message|
          %li= message
  %p
  .lin_gor
  %p.bottom_20
    .row
      .col-md-2
      .lin_ver
      .col-md-6
        = f.label :information_system
        = f.select :information_system_id, options_for_select(InformationSystem.all.map{|t| ["#{t.name} " , t.id]}, f.object.information_system_id),{include_blank: true},{class:"form-control selectpicker", data: {value: f.object.information_system_id}}
  
        = f.label :group_name
        = f.text_field :group_name, class:"form-control"
               
        = f.label :parameter
        = f.text_field :parameter, class:"form-control "
          
    %br
    .row
      .col-md-2
      .col-md-6.text-center.bottom_20
        -#.col-md-2.col-md-offset-2
        = link_to t('button.back'), group_rights_path, class: "btn btn-danger", style: "width: 15%; margin-right: 4%"
        -#.col-md-3
        = link_to_add_right_group_permition(f, f.object)
        -#.col-md-2
        = f.submit t('button.save'), class: "btn btn-primary", style: "width: 28%; margin-left: 4%"
        -#.col-md-3
    %p.bottom_20
    .row        
      = f.fields_for :right_group_permitions do |fn|
        .col-md-6
          .card.border-primary.mb-3
            .card-header
              .col-md-4
                %span.toright
                  = link_to_add_right_group_permition(f, f.object)
              .clearfix
            .card-body
              .row
                .col-md-10.col-md-offset-1
                  = fn.label :permition
                  = fn.select :permition_id,
                  options_for_select(Permition.all.map{|t| ["#{t.act} ", t.id]}, fn.object.permition_id),
                  {include_blank: true}, class:"form-control "
        
                  = fn.label :parameter
                  = fn.text_field :parameter, class:"form-control "

app/views/group_rights/edit.html.haml
%h1 Editing group_right

= render 'form'

= link_to 'Show', @group_right
\|
= link_to 'Back', group_rights_path

app/views/group_rights/index.html.haml
%h1= t("headers.#{params['controller']}.#{params['action']}")
.card.border-light.mb-3
  .card-header
    = link_to t('button.new.group_right'), new_group_right_path, class:"btn btn-success"
.table-responsive
  %table.table.table-hover.table-striped.my_table{style: "width:100%;"}
    %thead.thead-dark
      %tr
        %th №
        %th= t('activerecord.attributes.group_right.information_system')
        %th= t('activerecord.attributes.group_right.group_name')
        %th= t('activerecord.attributes.group_right.parameter')
        %th

    %tbody
      - @group_rights.each_with_index do |group_right, i|
        %tr
          %td
            =succeed '.' do
              =i + 1 + 10 * (@page.to_i - 1)
          %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{group_right.id}"]}}= group_right.information_system.name
          %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{group_right.id}"]}}= group_right.group_name
          %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{group_right.id}"]}}= group_right.parameter
          %td= link_to t('button.destroy'), group_right, method: :delete, data: { confirm: t('helpers.sure') }, class:"btn btn-danger"
= paginate @group_rights, id: "paginate"

app/views/group_rights/new.html.haml
%h1= t("headers.#{params['controller']}.#{params['action']}")

= render 'form'

app/views/group_rights/show.html.haml
%p#notice= notice

%p
  %b Information system:
  = @group_right.information_system
%p
  %b Group name:
  = @group_right.group_name
%p
  %b Parameter:
  = @group_right.parameter

= link_to 'Edit', edit_group_right_path(@group_right)
\|
= link_to 'Back', group_rights_path