config/routes.rb
Rails.application.routes.draw do
  get 'moderator/load_term_data_from_json', as: :term_data

  post 'moderator/load_term_data_from_json_commit', as: :term_data_commit

  devise_for :admins
  resources :permition_roles
  resources :right_group_permitions
  resources :role_group_rights
  resources :permitions
  resources :group_rights
  resources :role_users
  resources :dictionary_accesses do
    collection do
      get :get_table
    end
  end
  resources :information_systems
  resources :roles
  resources :users
  resources :branch_trees
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/right_group_permition.rb
class RightGroupPermition < ApplicationRecord
  belongs_to :permition
  belongs_to :group_right, inverse_of: :right_group_permitions
  
  validates :parameter, presence: true
end

app/controllers/right_group_permitions_controller.rb
class RightGroupPermitionsController < ApplicationController
  before_action :set_right_group_permition, only: [:show, :edit, :update, :destroy]

  # GET /right_group_permitions
  # GET /right_group_permitions.json
  def index
    @right_group_permitions = RightGroupPermition.all
  end

  # GET /right_group_permitions/1
  # GET /right_group_permitions/1.json
  def show
  end

  # GET /right_group_permitions/new
  def new
    @right_group_permition = RightGroupPermition.new
  end

  # GET /right_group_permitions/1/edit
  def edit
  end

  # POST /right_group_permitions
  # POST /right_group_permitions.json
  def create
    @right_group_permition = RightGroupPermition.new(right_group_permition_params)

    respond_to do |format|
      if @right_group_permition.save
        format.html { redirect_to @right_group_permition, notice: 'Right group permition was successfully created.' }
        format.json { render :show, status: :created, location: @right_group_permition }
      else
        format.html { render :new }
        format.json { render json: @right_group_permition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /right_group_permitions/1
  # PATCH/PUT /right_group_permitions/1.json
  def update
    respond_to do |format|
      if @right_group_permition.update(right_group_permition_params)
        format.html { redirect_to @right_group_permition, notice: 'Right group permition was successfully updated.' }
        format.json { render :show, status: :ok, location: @right_group_permition }
      else
        format.html { render :edit }
        format.json { render json: @right_group_permition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /right_group_permitions/1
  # DELETE /right_group_permitions/1.json
  def destroy
    @right_group_permition.destroy
    respond_to do |format|
      format.html { redirect_to right_group_permitions_url, notice: 'Right group permition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_right_group_permition
      @right_group_permition = RightGroupPermition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def right_group_permition_params
      params.require(:right_group_permition).permit(:permition_id, :group_right_id, :parameter)
    end
end

app/helpers/right_group_permitions_helper.rb
module RightGroupPermitionsHelper
  def link_to_add_right_group_permition(form, person)
    new_object = RightGroupPermition.new()
    fields = form.fields_for(:right_group_permitions, new_object, 
      :child_index => 'new_right_group_permition') do |builder|
      render('group_rights/add_right_group_permition', fn: builder)
    end
    link_to(?#, class: 'btn mbottom20 btn-info', 
        id: 'add_right_group_permition_link', data: {content: "#{fields}"}) do 
      " Новый комментарий" 
    end
  end
  
  def link_to_remove_right_group_permition(form)  
    form.hidden_field(:_destroy, class: 'remove_fields') + 
        link_to(?#, class: 'remove_fields remove_right_group_permition btn btn-danger') do 
          icon('fas', 'times')     
    end
  end
end

app/views/right_group_permitions/_form.html.haml
= form_for @right_group_permition do |f|
  - if @right_group_permition.errors.any?
    #error_explanation
      %h2= "#{pluralize(@right_group_permition.errors.count, "error")} prohibited this right_group_permition from being saved:"
      %ul
        - @right_group_permition.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :permition
    = f.text_field :permition
  .field
    = f.label :group_right
    = f.text_field :group_right
  .field
    = f.label :parameter
    = f.text_field :parameter  
  .actions
    = f.submit 'Save'

app/views/right_group_permitions/edit.html.haml
%h1 Editing right_group_permition

= render 'form'

= link_to 'Show', @right_group_permition
\|
= link_to 'Back', right_group_permitions_path

app/views/right_group_permitions/index.html.haml
%h1= t("headers.#{params['controller']}.#{params['action']}")
.card.border-light.mb-3
  .card-header
    = link_to 'New Right group permition', new_right_group_permition_path, class:"btn btn-success"
%table.table.table-hover.table-striped
  %thead.thead-dark
    %tr
      %th Permition
      %th Group right
      %th Parameter
      %th

  %tbody
    - @right_group_permitions.each do |right_group_permition|
      %tr
        %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{right_group_permition.id}"]}}= right_group_permition.permition.act
        %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{right_group_permition.id}"]}}= right_group_permition.group_right.group_name
        %td.user_row{"data" => {"content" => ["#{params['controller']}", "#{right_group_permition.id}"]}}= right_group_permition.parameter
        %td= link_to t('button.destroy'), right_group_permition, method: :delete, data: { confirm: t('helpers.sure') }, class:"btn btn-danger"

app/views/right_group_permitions/new.html.haml
%h1 New right_group_permition

= render 'form'

= link_to 'Back', right_group_permitions_path

app/views/right_group_permitions/show.html.haml
%p#notice= notice

%p
  %b Permition:
  = @right_group_permition.permition
%p
  %b Group right:
  = @right_group_permition.group_right
%p
  %b Parameter:
  = @right_group_permition.parameter

= link_to 'Edit', edit_right_group_permition_path(@right_group_permition)
\|
= link_to 'Back', right_group_permitions_path